---
title: "\U0001F335 Fractals"
date: "2021-01-24"
date-modified: today
order: 320
summary: An exploration of fractal shape and fractal math!
categories:
- fractals
- Iterated Functions
- Siepinski
- Mandelbrot
- Julia
---

```{r, echo=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(blogdown)
library(emoji)
#devtools::install_github("mccarthy-m-g/embedr")
library(embedr) # Embed multimedia in HTML files
```

#### A Geometric Jewellery Store

![Photo by
<a href="https://unsplash.com/@kolyakorzh?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mykola/Kolya
Korzh</a> on
<a href="https://unsplash.com/photos/brown-wooden-bird-house-ornament-HFogW6fHv4E?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>](featured.jpg)

## Introduction

Let us listen to the late great Benoit Mandelbrot, on the **Art of
Roughness**.

::: {}
<center>
{{< video https://www.youtube.com/watch?v=wQTnVEXAtBY width="560" height="480" >}}
The Art of Roughness
</center>
:::

## A Little ( just a little?) of Maths...

### What am $i$?

Dude, what's the square root of -1?? `r emoji::emoji("scream_cat")`
`r emoji::emoji("scream_cat")` `r emoji::emoji("scream_cat")`

What can you do repeatedly to arrive at $[-1, 0]$?

### Complex Planes

::: {}
<center>
{{< video https://www.youtube.com/watch?v=t75gXyWJNpA width="560" height="480" >}}
The Complex Plane
</center>
:::

### Julia, and Julia, and still more Julia....

::: {}
<center>
{{< video https://www.youtube.com/watch?v=2AZYZ-L8m9Q width="560" height="480" >}}
Julia, Julia, and Julia
</center>
:::
### Jewellery Shopping with Mandelbrot

Ever gone shopping for jewellery? How is the place organized? That is a
good metaphor for how Mandelbrot Set is generated!!

::: {}
<center>
{{< video https://www.youtube.com/watch?v=8ma6cV6fw24 width="560" height="480" >}}
The Mandelbrot Set
</center>
:::

<iframe width="100%" height="560" frameborder="0" src="https://observablehq.com/embed/@mcmcclur/julia-sets-and-the-mandelbrot-set?cells=topmatter%2Cwidget%2Cjulia_svg%2Ccompute_orbit">

</iframe>

## <u>[Wait, But Why?](https://waitbutwhy.com)</u>

To be Written Up.

## References

1.  Menger Sponge:
    <https://blogs.scientificamerican.com/roots-of-unity/a-few-of-my-favorite-spaces-the-menger-sponge/>

Use XaOS to make Mandelbrot and Julia fractals.
